/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'AC' : null } |
  { 'TV' : null } |
  { 'Laptop' : null } |
  { 'WashingMachine' : null } |
  { 'Refrigerator' : null } |
  { 'Mobile' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : bigint,
}
export interface StoreInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getStoreInfo' : ActorMethod<[], StoreInfo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];