/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'AC' : IDL.Null,
  'TV' : IDL.Null,
  'Laptop' : IDL.Null,
  'WashingMachine' : IDL.Null,
  'Refrigerator' : IDL.Null,
  'Mobile' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const StoreInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'AC' : IDL.Null,
    'TV' : IDL.Null,
    'Laptop' : IDL.Null,
    'WashingMachine' : IDL.Null,
    'Refrigerator' : IDL.Null,
    'Mobile' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const StoreInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };